baseURL: "https://jchun.me"
languageCode: en-us
title: jchun.me
theme: PaperMod

enableRobotsTXT: true
enableInlineShortcodes: true
enableEmoji: true

minify:
    disableXML: true
    minifyOutput: true

params:
    mainSections: posts
    assets:
        disableHLJS: true
    env: production
    cover:
        linkFullImages: true
    title: jchun.me
    author: Josh Chun
    DateFormat: "January 2, 2006"
    defaultTheme: dark
    ShowReadingTime: true
    ShowShareButtons: false
    ShowPostNavLinks: false
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    disableSpecial1stPost: false
    disableScrollToTop: false
    comments: true
    hidemeta: false
    hideSummary: false
    showtoc: false
    tocopen: false
    # Picture next to the home
    # label:
    #   text: "jchun.me"
    #   icon: beach3.jpg
    #   iconHeight: 35

    # home-info mode
    homeInfoParams:
        Title: "Welcome to my blog! \U0001F44B"
        Content:
            my name is joshua chun, and this is me.

    socialIcons:
        - name: github
          url: "https://github.com/joshhchun"
        - name: linkedin
          url: "https://www.linkedin.com/in/josh-chun-55254417a/"

menu:
    main:
        - indentifier: about
          name: about me
          url: /about/
          weight: 5
        - identifier: tech
          name: tech
          url: /posts/tech/
          weight: 10
        - identifier: life
          name: life
          url: /posts/life/
          weight: 15
        - indentifier: tags
          name: tags
          url: /tags/
          weight: 18
        - indentifier: archives
          name: archives
          url: /archives/
          weight: 20

markup:
    highlight:
        #anchorLineNos: false
        codeFences: true
        guessSyntax: true
        lineNos: false
        #pygmentsUseClasses: true
        #noClasses: true
        style: monokai
