baseURL: "https://jchun.me"
languageCode: en-us
title: jchun.me
theme: PaperMod

enableRobotsTXT: true
enableInlineShortcodes: true
enableEmoji: true

minify:
    disableXML: true
    minifyOutput: true

params:
    mainSections: posts
    env: production
    cover:
        linkFullImages: true
    title: jchun.me
    author: Josh Chun
    DateFormat: "January 2, 2006"
    defaultTheme: dark
    ShowReadingTime: true
    ShowShareButtons: false
    ShowPostNavLinks: false
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    disableSpecial1stPost: false
    disableScrollToTop: false
    comments: true
    hidemeta: false
    hideSummary: false
    showtoc: false
    tocopen: false
    assets:
        disableHLJS: true
        favicon: "<link / abs url>"
        favicon16x16: "<link / abs url>"
        favicon32x32: "<link / abs url>"
        apple_touch_icon: "<link / abs url>"
        safari_pinned_tab: "<link / abs url>"
    # label:
    #     text: "jchun.me"
    #     icon: favicon.ico
    #     iconHeight: 35

    # home-info mode
    homeInfoParams:
        Title: "Welcome to my blog! \U0001F44B"
        Content:
            "My name is Joshua Chun, and I am a rising Junior at the [University of Notre Dame](https://www.nd.edu). This
            is my personal website where I will be posting life updates, cool software-related findings, projects, and everything
            else in between."

    socialIcons:
        - name: github
          url: "https://github.com/joshhchun"
        - name: linkedin
          url: "https://www.linkedin.com/in/josh-chun-55254417a/"

menu:
    main:
        - indentifier: about
          name: about
          url: /about/
          weight: 5
        - indentifier: projects
          name: projects
          url: /posts/projects/
          weight: 6
        - identifier: tech
          name: posts
          url: /posts/tech/
          weight: 10
        # - identifier: life
        #   name: life
        #   url: /posts/life/
        #   weight: 15
        - indentifier: tags
          name: tags
          url: /tags/
          weight: 18
        - indentifier: archive
          name: archive
          url: /archives/
          weight: 20

markup:
    highlight:
        #anchorLineNos: false
        codeFences: true
        guessSyntax: true
        lineNos: false
        #pygmentsUseClasses: true
        #noClasses: true
        style: monokai
